/**
 * The generated half of `documentation/lint-results.md`: what the linters say
 * right now, and every place we told one of them to look away.
 *
 * Nobody keeps a list like this by hand for long. So the numbers and the
 * inventory are GENERATED, between two markers, and the prose around them —
 * the policy, and why each class of exception is accepted — stays written by
 * a person. The pre-commit hook runs this and stages the file, so every commit
 * says what it left unfixed.
 *
 * Deterministic on purpose: sorted, no timestamps, no line numbers (a warning
 * that moves down a file is the same warning), and no fallow health score,
 * which reads git churn and so changes with history rather than with code.
 * The file changes when a finding appears or goes away, and not otherwise.
 *
 * Usage:
 *
 *     node tools/quality/lintResults.ts           # rewrite the generated block
 *     node tools/quality/lintResults.ts --check   # exit 1 if it is stale
 */

import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";

const ROOT = process.cwd();
const DOC = path.join(ROOT, "documentation", "lint-results.md");
const BEGIN = "<!-- lint-results:begin (generated by `pnpm lint:results`; do not edit by hand) -->";
const END = "<!-- lint-results:end -->";

const run = (command: string, args: readonly string[]): string => {
  try {
    return execFileSync(command, args, {
      cwd: ROOT,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
  } catch (error) {
    // A linter that FOUND something exits non-zero; its report is still stdout.
    // SAFETY: execFileSync's thrown error carries the child's stdout as a field.
    const stdout = (error as { stdout?: unknown }).stdout;
    if (typeof stdout === "string" && stdout.trim() !== "") return stdout;
    throw error;
  }
};

const bin = (name: string): string => path.join(ROOT, "node_modules", ".bin", name);

// --- oxlint ---------------------------------------------------------------

interface OxDiagnostic {
  readonly code?: string;
  readonly severity?: string;
  readonly filename?: string;
  readonly message?: string;
}

const oxlint = (): readonly OxDiagnostic[] => {
  const parsed: unknown = JSON.parse(run(bin("oxlint"), ["-f", "json", "."]));
  // SAFETY: oxlint's own JSON reporter; every field is read as optional.
  return (parsed as { diagnostics?: readonly OxDiagnostic[] }).diagnostics ?? [];
};

// --- suppressions in source -----------------------------------------------

const SUPPRESSION =
  /(fallow-ignore(?:-file|-next-line)?|oxlint-disable(?:-next-line|-line)?|eslint-disable(?:-next-line|-line)?|@ts-expect-error|@ts-ignore)\b(.*)$/u;

const SOURCE = new Set([".ts", ".tsx", ".mts", ".cts", ".js", ".mjs"]);
const GENERATED = /\.gen\.[a-z]+$/u;

const walk = (directory: string, out: string[]): void => {
  if (!statSync(directory, { throwIfNoEntry: false })?.isDirectory()) return;
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name.startsWith(".")) continue;
    const full = path.join(directory, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (SOURCE.has(path.extname(entry.name)) && !GENERATED.test(entry.name)) out.push(full);
  }
};

interface Suppression {
  readonly file: string;
  readonly kind: string;
  readonly detail: string;
}

const suppressions = (): readonly Suppression[] => {
  const files: string[] = [];
  for (const top of ["src", "tools", "e2e", "workers"]) walk(path.join(ROOT, top), files);
  const found: Suppression[] = [];
  for (const file of files) {
    for (const line of readFileSync(file, "utf8").split("\n")) {
      const comment = line.indexOf("//") === -1 ? line.indexOf("/*") : line.indexOf("//");
      if (comment === -1) continue;
      const match = SUPPRESSION.exec(line.slice(comment));
      if (match === null) continue;
      found.push({
        file: path.relative(ROOT, file),
        kind: match[1] ?? "",
        detail: (match[2] ?? "").replace(/\*\/\s*$/u, "").trim(),
      });
    }
  }
  return found.sort((a, b) => a.file.localeCompare(b.file) || a.kind.localeCompare(b.kind));
};

// --- fallow ---------------------------------------------------------------

const fallowConfig = (): { entry: readonly string[]; ignoreDependencies: readonly string[] } => {
  const text = readFileSync(path.join(ROOT, ".fallowrc.jsonc"), "utf8")
    .replace(/^\s*\/\/.*$/gmu, "")
    .replace(/,(\s*[}\]])/gu, "$1");
  // SAFETY: this repository's own config; both fields are optional string lists.
  const parsed = JSON.parse(text) as { entry?: string[]; ignoreDependencies?: string[] };
  return { entry: parsed.entry ?? [], ignoreDependencies: parsed.ignoreDependencies ?? [] };
};

const deadCodeIssues = (): number => {
  const parsed: unknown = JSON.parse(
    run(bin("fallow"), [
      "dead-code",
      "--unused-files",
      "--unused-exports",
      "--unused-types",
      "--unused-deps",
      "--circular-deps",
      "--format",
      "json",
      "--quiet",
    ]),
  );
  // SAFETY: fallow's JSON report; `total_issues` is its own summary count.
  return (parsed as { total_issues?: number }).total_issues ?? 0;
};

const duplication = (): { percent: string; groups: number } => {
  const parsed: unknown = JSON.parse(run(bin("fallow"), ["dupes", "--format", "json", "--quiet"]));
  // SAFETY: fallow's JSON report; both fields are read defensively.
  const report = parsed as {
    stats?: { duplication_percentage?: number };
    clone_groups?: readonly unknown[];
  };
  const percent = report.stats?.duplication_percentage;
  return {
    percent: typeof percent === "number" ? `${percent.toFixed(1)}%` : "unknown",
    groups: report.clone_groups?.length ?? 0,
  };
};

// --- render ---------------------------------------------------------------

const render = (): string => {
  const lines: string[] = [];
  const diagnostics = oxlint();
  const errors = diagnostics.filter((d) => d.severity === "error").length;
  const warnings = diagnostics.filter((d) => d.severity !== "error");
  const dead = deadCodeIssues();
  const dupes = duplication();
  const config = fallowConfig();
  const held = suppressions();

  lines.push("### Numbers", "");
  lines.push("| check | result | gate |", "| --- | --- | --- |");
  lines.push(`| oxlint errors | ${errors} | \`pnpm lint\`, every commit |`);
  lines.push(`| oxlint warnings | ${warnings.length} | none — listed below |`);
  lines.push(
    `| fallow dead code (\`pnpm deadcode\`) | ${dead} issue(s) | every deploy; advisory on branches |`,
  );
  lines.push(
    `| fallow duplication | ${dupes.percent} in ${dupes.groups} clone group(s) | none — advisory |`,
  );
  lines.push(`| suppression comments | ${held.length} | each listed below with its reason |`);
  lines.push("");

  lines.push("### Oxlint warnings, by rule and file", "");
  if (warnings.length === 0) lines.push("None.", "");
  else {
    const byRule = new Map<string, Map<string, number>>();
    for (const warning of warnings) {
      const rule = warning.code ?? "unknown";
      const files = byRule.get(rule) ?? new Map<string, number>();
      const file = warning.filename ?? "unknown";
      files.set(file, (files.get(file) ?? 0) + 1);
      byRule.set(rule, files);
    }
    for (const rule of [...byRule.keys()].sort()) {
      const files = byRule.get(rule) ?? new Map<string, number>();
      const total = [...files.values()].reduce((sum, n) => sum + n, 0);
      lines.push(`**\`${rule}\`** — ${total}`, "");
      for (const file of [...files.keys()].sort()) lines.push(`- \`${file}\` × ${files.get(file)}`);
      lines.push("");
    }
  }

  lines.push("### Suppression comments", "");
  if (held.length === 0) lines.push("None.", "");
  else {
    lines.push("| file | suppresses | says |", "| --- | --- | --- |");
    for (const one of held)
      lines.push(
        `| \`${one.file}\` | \`${one.kind}\` | ${one.detail.replace(/\|/gu, "\\|") || "—"} |`,
      );
    lines.push("");
  }

  lines.push("### Fallow configuration exceptions", "");
  lines.push("From `.fallowrc.jsonc`, where each one's reason is written beside it.", "");
  lines.push(`- **Extra entries:** ${config.entry.map((e) => `\`${e}\``).join(", ") || "none"}`);
  lines.push(
    `- **Dependencies it cannot see used:** ${config.ignoreDependencies.map((d) => `\`${d}\``).join(", ") || "none"}`,
  );
  lines.push("");
  return lines.join("\n");
};

const main = (): void => {
  const check = process.argv.includes("--check");
  const current = readFileSync(DOC, "utf8");
  const start = current.indexOf(BEGIN);
  const stop = current.indexOf(END);
  if (start === -1 || stop === -1 || stop < start)
    throw new Error(`lint-results: ${path.relative(ROOT, DOC)} has lost its markers`);
  const next = `${current.slice(0, start + BEGIN.length)}\n\n${render()}\n${current.slice(stop)}`;
  if (next === current) {
    process.stdout.write("lint-results: up to date\n");
    return;
  }
  if (check) {
    process.stderr.write("lint-results: stale — run `pnpm lint:results`\n");
    process.exitCode = 1;
    return;
  }
  writeFileSync(DOC, next);
  process.stdout.write(`lint-results: wrote ${path.relative(ROOT, DOC)}\n`);
};

main();
