import { RouterProvider, createRouter } from "@tanstack/solid-router";
import { Result } from "effect";
import { Show } from "solid-js";

import { composeApplication } from "#app/composition";
import { CompositionProvider, useComposition } from "#app/CompositionContext";
import { DelayedSpinner, PENDING_MS } from "#app/ui/primitives";

import "#app/ui/app.css";

// Generated by @tanstack/router-plugin from the files under src/routes —
// TanStack derives full typesafety for <Link>, params, and loader data
// from this tree.
import { routeTree } from "./routeTree.gen";

// One wait, one look: blank, and a spinner only past `PENDING_MS`. The router's
// own threshold is the same number, but it does not cover everything — a route
// chunk still loading suspends straight to this component — so the component
// holds the delay itself too.
const router = createRouter({
  routeTree,
  defaultPendingMs: PENDING_MS,
  defaultPendingComponent: DelayedSpinner,
});

// Registers the router's types library-wide, so `to`/`params` on every
// <Link> typecheck against the actual routes.
declare module "@tanstack/solid-router" {
  interface Register {
    router: typeof router;
  }
}

// The one composition. Nothing else in the tree composes; every consumer
// reaches these services through useComposition(). The await is top-level
// because the dev-only OTLP Layer builds asynchronously, and the plugin's
// generated client entry supports it.
const composition = await composeApplication();

function Shell() {
  const composed = useComposition();
  const booted = Result.isSuccess(composed.boot) ? composed.boot.success : null;
  const bootErrorTag = Result.isFailure(composed.boot) ? composed.boot.failure._tag : "";

  return (
    <Show
      when={booted}
      fallback={<main data-boot-error={bootErrorTag}>boot failed: {bootErrorTag}</main>}
    >
      {(info) => (
        <>
          <div data-host={info().host} data-build={info().build} data-boot-phase={info().phase} />
          <RouterProvider router={router} />
        </>
      )}
    </Show>
  );
}

// The app root: the plugin's generated entries render this component,
// wrapped in src/Document.tsx.
export default function App() {
  return (
    <CompositionProvider value={composition}>
      <Shell />
    </CompositionProvider>
  );
}
