import { RouterProvider, createRouter } from "@tanstack/solid-router";
import { Result } from "effect";
import { Show } from "solid-js";

import { applicationBoot } from "./app/composition";

import "./App.css";

// Generated by @tanstack/router-plugin from the files under src/routes —
// TanStack derives full typesafety for <Link>, params, and loader data
// from this tree.
import { routeTree } from "./routeTree.gen";

if (import.meta.env.DEV) {
  const { installDevRoutes } = await import("./routes/dev/register");
  installDevRoutes(routeTree);
}

const router = createRouter({
  routeTree,
  defaultPendingComponent: () => <main>Loading…</main>,
});

// Registers the router's types library-wide, so `to`/`params` on every
// <Link> typecheck against the actual routes.
declare module "@tanstack/solid-router" {
  interface Register {
    router: typeof router;
  }
}

const bootedInfo = Result.isSuccess(applicationBoot) ? applicationBoot.success : null;
const bootErrorTag = Result.isFailure(applicationBoot) ? applicationBoot.failure._tag : "";

// The app root: the plugin's generated entries render this component,
// wrapped in src/Document.tsx.
export default function App() {
  return (
    <Show
      when={bootedInfo}
      fallback={<main data-boot-error={bootErrorTag}>boot failed: {bootErrorTag}</main>}
    >
      {(info) => (
        <>
          <div data-host={info().host} data-build={info().build} data-boot-phase={info().phase} />
          <RouterProvider router={router} />
        </>
      )}
    </Show>
  );
}
