/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DesignRouteImport } from './routes/design'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDevFixtureRouteImport } from './routes/_app/dev/fixture'
import { Route as AppProjectSlugRouteImport } from './routes/_app/project/$slug'
import { Route as AppStartCreateRouteImport } from './routes/_app/start/create'
import { Route as AppStartFindRouteImport } from './routes/_app/start/find'
import { Route as AppProjectSlugIndexRouteImport } from './routes/_app/project/$slug/index'
import { Route as AppProjectSlugCloudRouteImport } from './routes/_app/project/$slug/cloud'
import { Route as AppProjectSlugCompareRouteImport } from './routes/_app/project/$slug/compare'
import { Route as AppProjectSlugFindRouteImport } from './routes/_app/project/$slug/find'
import { Route as AppProjectSlugFindingsRouteImport } from './routes/_app/project/$slug/findings'
import { Route as AppProjectSlugHistoryRouteImport } from './routes/_app/project/$slug/history'
import { Route as AppProjectSlugInventoryRouteImport } from './routes/_app/project/$slug/inventory'
import { Route as AppProjectSlugPlaygroundRouteImport } from './routes/_app/project/$slug/playground'
import { Route as AppProjectSlugReviewRouteImport } from './routes/_app/project/$slug/review'
import { Route as AppProjectSlugTermsRouteImport } from './routes/_app/project/$slug/terms'
import { Route as AppProjectSlugBookBookRouteImport } from './routes/_app/project/$slug/book/$book'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDevFixtureRoute = AppDevFixtureRouteImport.update({
  id: '/dev/fixture',
  path: '/dev/fixture',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectSlugRoute = AppProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppStartCreateRoute = AppStartCreateRouteImport.update({
  id: '/start/create',
  path: '/start/create',
  getParentRoute: () => AppRoute,
} as any)
const AppStartFindRoute = AppStartFindRouteImport.update({
  id: '/start/find',
  path: '/start/find',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectSlugIndexRoute = AppProjectSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectSlugRoute,
} as any)
const AppProjectSlugCloudRoute = AppProjectSlugCloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => AppProjectSlugRoute,
} as any)
const AppProjectSlugCompareRoute = AppProjectSlugCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppProjectSlugRoute,
} as any)
const AppProjectSlugFindRoute = AppProjectSlugFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => AppProjectSlugRoute,
} as any)
const AppProjectSlugFindingsRoute = AppProjectSlugFindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => AppProjectSlugRoute,
} as any)
const AppProjectSlugHistoryRoute = AppProjectSlugHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppProjectSlugRoute,
} as any)
const AppProjectSlugInventoryRoute = AppProjectSlugInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppProjectSlugRoute,
} as any)
const AppProjectSlugPlaygroundRoute =
  AppProjectSlugPlaygroundRouteImport.update({
    id: '/playground',
    path: '/playground',
    getParentRoute: () => AppProjectSlugRoute,
  } as any)
const AppProjectSlugReviewRoute = AppProjectSlugReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppProjectSlugRoute,
} as any)
const AppProjectSlugTermsRoute = AppProjectSlugTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppProjectSlugRoute,
} as any)
const AppProjectSlugBookBookRoute = AppProjectSlugBookBookRouteImport.update({
  id: '/book/$book',
  path: '/book/$book',
  getParentRoute: () => AppProjectSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/design': typeof DesignRoute
  '/projects': typeof AppProjectsRoute
  '/settings': typeof AppSettingsRoute
  '/dev/fixture': typeof AppDevFixtureRoute
  '/project/$slug': typeof AppProjectSlugRouteWithChildren
  '/start/create': typeof AppStartCreateRoute
  '/start/find': typeof AppStartFindRoute
  '/project/$slug/cloud': typeof AppProjectSlugCloudRoute
  '/project/$slug/compare': typeof AppProjectSlugCompareRoute
  '/project/$slug/find': typeof AppProjectSlugFindRoute
  '/project/$slug/findings': typeof AppProjectSlugFindingsRoute
  '/project/$slug/history': typeof AppProjectSlugHistoryRoute
  '/project/$slug/inventory': typeof AppProjectSlugInventoryRoute
  '/project/$slug/playground': typeof AppProjectSlugPlaygroundRoute
  '/project/$slug/review': typeof AppProjectSlugReviewRoute
  '/project/$slug/terms': typeof AppProjectSlugTermsRoute
  '/project/$slug/': typeof AppProjectSlugIndexRoute
  '/project/$slug/book/$book': typeof AppProjectSlugBookBookRoute
}
export interface FileRoutesByTo {
  '/design': typeof DesignRoute
  '/projects': typeof AppProjectsRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/dev/fixture': typeof AppDevFixtureRoute
  '/start/create': typeof AppStartCreateRoute
  '/start/find': typeof AppStartFindRoute
  '/project/$slug/cloud': typeof AppProjectSlugCloudRoute
  '/project/$slug/compare': typeof AppProjectSlugCompareRoute
  '/project/$slug/find': typeof AppProjectSlugFindRoute
  '/project/$slug/findings': typeof AppProjectSlugFindingsRoute
  '/project/$slug/history': typeof AppProjectSlugHistoryRoute
  '/project/$slug/inventory': typeof AppProjectSlugInventoryRoute
  '/project/$slug/playground': typeof AppProjectSlugPlaygroundRoute
  '/project/$slug/review': typeof AppProjectSlugReviewRoute
  '/project/$slug/terms': typeof AppProjectSlugTermsRoute
  '/project/$slug': typeof AppProjectSlugIndexRoute
  '/project/$slug/book/$book': typeof AppProjectSlugBookBookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/design': typeof DesignRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/dev/fixture': typeof AppDevFixtureRoute
  '/_app/project/$slug': typeof AppProjectSlugRouteWithChildren
  '/_app/start/create': typeof AppStartCreateRoute
  '/_app/start/find': typeof AppStartFindRoute
  '/_app/project/$slug/cloud': typeof AppProjectSlugCloudRoute
  '/_app/project/$slug/compare': typeof AppProjectSlugCompareRoute
  '/_app/project/$slug/find': typeof AppProjectSlugFindRoute
  '/_app/project/$slug/findings': typeof AppProjectSlugFindingsRoute
  '/_app/project/$slug/history': typeof AppProjectSlugHistoryRoute
  '/_app/project/$slug/inventory': typeof AppProjectSlugInventoryRoute
  '/_app/project/$slug/playground': typeof AppProjectSlugPlaygroundRoute
  '/_app/project/$slug/review': typeof AppProjectSlugReviewRoute
  '/_app/project/$slug/terms': typeof AppProjectSlugTermsRoute
  '/_app/project/$slug/': typeof AppProjectSlugIndexRoute
  '/_app/project/$slug/book/$book': typeof AppProjectSlugBookBookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/projects'
    | '/settings'
    | '/dev/fixture'
    | '/project/$slug'
    | '/start/create'
    | '/start/find'
    | '/project/$slug/cloud'
    | '/project/$slug/compare'
    | '/project/$slug/find'
    | '/project/$slug/findings'
    | '/project/$slug/history'
    | '/project/$slug/inventory'
    | '/project/$slug/playground'
    | '/project/$slug/review'
    | '/project/$slug/terms'
    | '/project/$slug/'
    | '/project/$slug/book/$book'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/design'
    | '/projects'
    | '/settings'
    | '/'
    | '/dev/fixture'
    | '/start/create'
    | '/start/find'
    | '/project/$slug/cloud'
    | '/project/$slug/compare'
    | '/project/$slug/find'
    | '/project/$slug/findings'
    | '/project/$slug/history'
    | '/project/$slug/inventory'
    | '/project/$slug/playground'
    | '/project/$slug/review'
    | '/project/$slug/terms'
    | '/project/$slug'
    | '/project/$slug/book/$book'
  id:
    | '__root__'
    | '/_app'
    | '/design'
    | '/_app/projects'
    | '/_app/settings'
    | '/_app/'
    | '/_app/dev/fixture'
    | '/_app/project/$slug'
    | '/_app/start/create'
    | '/_app/start/find'
    | '/_app/project/$slug/cloud'
    | '/_app/project/$slug/compare'
    | '/_app/project/$slug/find'
    | '/_app/project/$slug/findings'
    | '/_app/project/$slug/history'
    | '/_app/project/$slug/inventory'
    | '/_app/project/$slug/playground'
    | '/_app/project/$slug/review'
    | '/_app/project/$slug/terms'
    | '/_app/project/$slug/'
    | '/_app/project/$slug/book/$book'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  DesignRoute: typeof DesignRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dev/fixture': {
      id: '/_app/dev/fixture'
      path: '/dev/fixture'
      fullPath: '/dev/fixture'
      preLoaderRoute: typeof AppDevFixtureRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/project/$slug': {
      id: '/_app/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof AppProjectSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/start/create': {
      id: '/_app/start/create'
      path: '/start/create'
      fullPath: '/start/create'
      preLoaderRoute: typeof AppStartCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/start/find': {
      id: '/_app/start/find'
      path: '/start/find'
      fullPath: '/start/find'
      preLoaderRoute: typeof AppStartFindRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/project/$slug/': {
      id: '/_app/project/$slug/'
      path: '/'
      fullPath: '/project/$slug/'
      preLoaderRoute: typeof AppProjectSlugIndexRouteImport
      parentRoute: typeof AppProjectSlugRoute
    }
    '/_app/project/$slug/cloud': {
      id: '/_app/project/$slug/cloud'
      path: '/cloud'
      fullPath: '/project/$slug/cloud'
      preLoaderRoute: typeof AppProjectSlugCloudRouteImport
      parentRoute: typeof AppProjectSlugRoute
    }
    '/_app/project/$slug/compare': {
      id: '/_app/project/$slug/compare'
      path: '/compare'
      fullPath: '/project/$slug/compare'
      preLoaderRoute: typeof AppProjectSlugCompareRouteImport
      parentRoute: typeof AppProjectSlugRoute
    }
    '/_app/project/$slug/find': {
      id: '/_app/project/$slug/find'
      path: '/find'
      fullPath: '/project/$slug/find'
      preLoaderRoute: typeof AppProjectSlugFindRouteImport
      parentRoute: typeof AppProjectSlugRoute
    }
    '/_app/project/$slug/findings': {
      id: '/_app/project/$slug/findings'
      path: '/findings'
      fullPath: '/project/$slug/findings'
      preLoaderRoute: typeof AppProjectSlugFindingsRouteImport
      parentRoute: typeof AppProjectSlugRoute
    }
    '/_app/project/$slug/history': {
      id: '/_app/project/$slug/history'
      path: '/history'
      fullPath: '/project/$slug/history'
      preLoaderRoute: typeof AppProjectSlugHistoryRouteImport
      parentRoute: typeof AppProjectSlugRoute
    }
    '/_app/project/$slug/inventory': {
      id: '/_app/project/$slug/inventory'
      path: '/inventory'
      fullPath: '/project/$slug/inventory'
      preLoaderRoute: typeof AppProjectSlugInventoryRouteImport
      parentRoute: typeof AppProjectSlugRoute
    }
    '/_app/project/$slug/playground': {
      id: '/_app/project/$slug/playground'
      path: '/playground'
      fullPath: '/project/$slug/playground'
      preLoaderRoute: typeof AppProjectSlugPlaygroundRouteImport
      parentRoute: typeof AppProjectSlugRoute
    }
    '/_app/project/$slug/review': {
      id: '/_app/project/$slug/review'
      path: '/review'
      fullPath: '/project/$slug/review'
      preLoaderRoute: typeof AppProjectSlugReviewRouteImport
      parentRoute: typeof AppProjectSlugRoute
    }
    '/_app/project/$slug/terms': {
      id: '/_app/project/$slug/terms'
      path: '/terms'
      fullPath: '/project/$slug/terms'
      preLoaderRoute: typeof AppProjectSlugTermsRouteImport
      parentRoute: typeof AppProjectSlugRoute
    }
    '/_app/project/$slug/book/$book': {
      id: '/_app/project/$slug/book/$book'
      path: '/book/$book'
      fullPath: '/project/$slug/book/$book'
      preLoaderRoute: typeof AppProjectSlugBookBookRouteImport
      parentRoute: typeof AppProjectSlugRoute
    }
  }
}

interface AppProjectSlugRouteChildren {
  AppProjectSlugCloudRoute: typeof AppProjectSlugCloudRoute
  AppProjectSlugCompareRoute: typeof AppProjectSlugCompareRoute
  AppProjectSlugFindRoute: typeof AppProjectSlugFindRoute
  AppProjectSlugFindingsRoute: typeof AppProjectSlugFindingsRoute
  AppProjectSlugHistoryRoute: typeof AppProjectSlugHistoryRoute
  AppProjectSlugInventoryRoute: typeof AppProjectSlugInventoryRoute
  AppProjectSlugPlaygroundRoute: typeof AppProjectSlugPlaygroundRoute
  AppProjectSlugReviewRoute: typeof AppProjectSlugReviewRoute
  AppProjectSlugTermsRoute: typeof AppProjectSlugTermsRoute
  AppProjectSlugIndexRoute: typeof AppProjectSlugIndexRoute
  AppProjectSlugBookBookRoute: typeof AppProjectSlugBookBookRoute
}

const AppProjectSlugRouteChildren: AppProjectSlugRouteChildren = {
  AppProjectSlugCloudRoute: AppProjectSlugCloudRoute,
  AppProjectSlugCompareRoute: AppProjectSlugCompareRoute,
  AppProjectSlugFindRoute: AppProjectSlugFindRoute,
  AppProjectSlugFindingsRoute: AppProjectSlugFindingsRoute,
  AppProjectSlugHistoryRoute: AppProjectSlugHistoryRoute,
  AppProjectSlugInventoryRoute: AppProjectSlugInventoryRoute,
  AppProjectSlugPlaygroundRoute: AppProjectSlugPlaygroundRoute,
  AppProjectSlugReviewRoute: AppProjectSlugReviewRoute,
  AppProjectSlugTermsRoute: AppProjectSlugTermsRoute,
  AppProjectSlugIndexRoute: AppProjectSlugIndexRoute,
  AppProjectSlugBookBookRoute: AppProjectSlugBookBookRoute,
}

const AppProjectSlugRouteWithChildren = AppProjectSlugRoute._addFileChildren(
  AppProjectSlugRouteChildren,
)

interface AppRouteChildren {
  AppProjectsRoute: typeof AppProjectsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDevFixtureRoute: typeof AppDevFixtureRoute
  AppProjectSlugRoute: typeof AppProjectSlugRouteWithChildren
  AppStartCreateRoute: typeof AppStartCreateRoute
  AppStartFindRoute: typeof AppStartFindRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProjectsRoute: AppProjectsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppDevFixtureRoute: AppDevFixtureRoute,
  AppProjectSlugRoute: AppProjectSlugRouteWithChildren,
  AppStartCreateRoute: AppStartCreateRoute,
  AppStartFindRoute: AppStartFindRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DesignRoute: DesignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
